// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Tmail",
            "url": "https://github.com/sunls24/tmail"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/domain": {
            "get": {
                "description": "Returns a list of available email domain suffixes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domain"
                ],
                "summary": "Get available domains",
                "responses": {
                    "200": {
                        "description": "List of available domains",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/download/{id}": {
            "get": {
                "description": "Download an email attachment by its ID",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Download attachment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attachment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Attachment file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Attachment not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/fetch": {
            "get": {
                "description": "Fetch all emails for a specific address. If the address is the admin address, returns the latest 100 emails from all addresses.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Fetch emails",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address to fetch emails for",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of emails",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ent.Envelope"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/fetch/latest": {
            "get": {
                "description": "Long polling endpoint to wait for new emails. Returns immediately if there's a new email with ID greater than the provided ID. Otherwise, waits up to 60 seconds for a new email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Long polling for new emails",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address to watch for new emails",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Last known email ID (returns emails newer than this)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New email received",
                        "schema": {
                            "$ref": "#/definitions/ent.Envelope"
                        }
                    },
                    "204": {
                        "description": "No new email within timeout period"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/fetch/{id}": {
            "get": {
                "description": "Get the full content and attachments of a specific email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Fetch email detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Email ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email detail with content and attachments",
                        "schema": {
                            "$ref": "#/definitions/api.MailDetail"
                        }
                    },
                    "400": {
                        "description": "Bad request or email not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/report": {
            "post": {
                "description": "Internal endpoint - Used by Cloudflare Workers to report incoming emails. This endpoint receives raw email data in MIME format and stores it in the database.",
                "consumes": [
                    "*/*"
                ],
                "tags": [
                    "Internal"
                ],
                "summary": "Report incoming email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipient email address",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email successfully stored"
                    },
                    "400": {
                        "description": "Failed to process email"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AttachmentDetail": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "api.MailDetail": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.AttachmentDetail"
                    }
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "ent.Attachment": {
            "type": "object",
            "properties": {
                "contentType": {
                    "description": "ContentType holds the value of the \"contentType\" field.",
                    "type": "string"
                },
                "edges": {
                    "description": "Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the AttachmentQuery when eager-loading is set.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.AttachmentEdges"
                        }
                    ]
                },
                "filename": {
                    "description": "Filename holds the value of the \"filename\" field.",
                    "type": "string"
                },
                "filepath": {
                    "description": "Filepath holds the value of the \"filepath\" field.",
                    "type": "string"
                },
                "id": {
                    "description": "ID of the ent.",
                    "type": "string"
                }
            }
        },
        "ent.AttachmentEdges": {
            "type": "object",
            "properties": {
                "owner": {
                    "description": "Owner holds the value of the owner edge.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.Envelope"
                        }
                    ]
                }
            }
        },
        "ent.Envelope": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Content holds the value of the \"content\" field.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt holds the value of the \"created_at\" field.",
                    "type": "string"
                },
                "edges": {
                    "description": "Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the EnvelopeQuery when eager-loading is set.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.EnvelopeEdges"
                        }
                    ]
                },
                "from": {
                    "description": "From holds the value of the \"from\" field.",
                    "type": "string"
                },
                "id": {
                    "description": "ID of the ent.",
                    "type": "integer"
                },
                "subject": {
                    "description": "Subject holds the value of the \"subject\" field.",
                    "type": "string"
                },
                "to": {
                    "description": "To holds the value of the \"to\" field.",
                    "type": "string"
                }
            }
        },
        "ent.EnvelopeEdges": {
            "type": "object",
            "properties": {
                "attachments": {
                    "description": "Attachments holds the value of the attachments edge.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ent.Attachment"
                    }
                }
            }
        }
    },
    "tags": [
        {
            "description": "Email operations",
            "name": "Email"
        },
        {
            "description": "Domain operations",
            "name": "Domain"
        },
        {
            "description": "Internal operations (used by Cloudflare Workers)",
            "name": "Internal"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Tmail API",
	Description:      "API documentation for Tmail - Anonymous Temporary Email Service.\nTmail provides a simple API to receive and manage temporary emails.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
